package view;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.DAO.EntradaDAO;
import model.DAO.SaidaDAO;
import model.DAO.TipoEntradaDAO;
import model.bean.Entrada;
import model.bean.Saida;
import model.bean.TipoEntrada;
import Calculo.Saldo;
import java.time.Month;
import javax.swing.JPanel;
import model.DAO.AnoDataDAO;
import model.DAO.MesDataDAO;
import model.bean.AnoData;
import model.bean.MesData;

public class ConsultaSaldo extends javax.swing.JInternalFrame {

    private double totalentradas = 0;
    private double totalsaidas = 0;
    private double totalsaldo = 0;

   
    
    public ConsultaSaldo() {
        initComponents();
        
        DefaultTableModel modeloE = (DefaultTableModel) jTentradas.getModel();
        jTentradas.setRowSorter(new TableRowSorter(modeloE));

        readJTableE();
        
        DefaultTableModel modeloS = (DefaultTableModel) jTsaidas.getModel();
        jTsaidas.setRowSorter(new TableRowSorter(modeloS));
        
        readJTableS();

        Saldo s = new Saldo(totalentradas, totalsaidas);
        txtValorSaldo.setText(s.toString());

        CBdata();
        
        Date myDate = new Date();
        String dStr = new SimpleDateFormat("yyyy-MM-dd").format(myDate);
        jTdataA.setText(dStr);
        jTdataDe.setText(String.valueOf(myDate.getYear()+1900) +"-"+ String.valueOf(myDate.getMonth()+1)+"-01");
        
       
    }

    
    public void CBdata() {
        //MesDataDAO mdao = new MesDataDAO();
        AnoDataDAO adao = new AnoDataDAO();
        //jCBmes.addItem("");
        /**
        for(MesData m: mdao.read_distint_mes()){
            jCBmes.addItem(m.getNomemes());
        }
        **/ 
        jCBmes.addItem("");
        jCBmes.addItem("Janeiro");
        jCBmes.addItem("Fevereiro");
        jCBmes.addItem("Março");
        jCBmes.addItem("Abril");
        jCBmes.addItem("Maio");
        jCBmes.addItem("Junho");
        jCBmes.addItem("Julho");
        jCBmes.addItem("Agosto");        
        jCBmes.addItem("Setembro");
        jCBmes.addItem("Outubro");
        jCBmes.addItem("Novembro");        
        jCBmes.addItem("Dezembro");
        
        jCBano.addItem("");
        for(AnoData a: adao.read_distint_ano()){
            jCBano.addItem(String.valueOf(a.getAno()));
        }
    }
    
    public void readJTableE() {
        
        DefaultTableModel modeloE = (DefaultTableModel) jTentradas.getModel();
        modeloE.setNumRows(0);
        EntradaDAO edao = new EntradaDAO();
        totalentradas = 0;
        String idte ="*";
        
        for (Entrada e : edao.read_testr(idte)) {

            modeloE.addRow(new Object[]{
                e.getId(),
                e.getDes_entrada(),
                e.getData(),
                e.getValor()
                               
            });
        totalentradas=totalentradas+e.getValor();
        }
        txtValorTotalEntradas.setText(String.format("%.2f €",totalentradas));
    }

      public void readJTableS() {
        
        DefaultTableModel modeloS = (DefaultTableModel) jTsaidas.getModel();
        modeloS.setNumRows(0);
        SaidaDAO sdao = new SaidaDAO();
        totalsaidas = 0;
        String idts ="*";
        for (Saida s : sdao.read_testr(idts)) {

            modeloS.addRow(new Object[]{
                s.getId(),
                s.getDes_saida(),
                s.getData(),
                s.getValor()
                               
            });
        totalsaidas=totalsaidas+s.getValor();
        }
        txtValorTotalSaidas.setText(String.format("%.2f €",totalsaidas));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTentradas = new javax.swing.JTable();
        txtValorTotalEntradas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTsaidas = new javax.swing.JTable();
        txtValorTotalSaidas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtValorSaldo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBmes = new javax.swing.JButton();
        jTdataDe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTdataA = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCBano = new javax.swing.JComboBox<>();
        jCBmes = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setClosable(true);
        setTitle("Consulta Saldo");

        jTentradas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tipo Entrada", "Data", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTentradas);
        if (jTentradas.getColumnModel().getColumnCount() > 0) {
            jTentradas.getColumnModel().getColumn(0).setMinWidth(20);
            jTentradas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTentradas.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        txtValorTotalEntradas.setEditable(false);
        txtValorTotalEntradas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel1.setText("Total Entradas");

        jTsaidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Tipo Saida", "Data", "Valor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTsaidas);
        if (jTsaidas.getColumnModel().getColumnCount() > 0) {
            jTsaidas.getColumnModel().getColumn(0).setMinWidth(20);
            jTsaidas.getColumnModel().getColumn(0).setPreferredWidth(50);
            jTsaidas.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        txtValorTotalSaidas.setEditable(false);
        txtValorTotalSaidas.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel2.setText("Total Saidas");

        txtValorSaldo.setEditable(false);
        txtValorSaldo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel3.setText("Saldo");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorTotalEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorTotalSaidas, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtValorSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtValorSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValorTotalEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtValorTotalSaidas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))))
        );

        jBmes.setText("Pesquisa por data");
        jBmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBmesActionPerformed(evt);
            }
        });

        jTdataDe.setText("aaaa-MM-dd");

        jLabel4.setText("De");

        jTdataA.setText("aaaa-MM-dd");

        jLabel5.setText("a");

        jCBano.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBanoItemStateChanged(evt);
            }
        });

        jCBmes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBmesItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(313, 313, 313)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCBmes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTdataDe, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTdataA, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCBano, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jBmes)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTdataA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jTdataDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCBmes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCBano, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jBmes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCBmesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBmesItemStateChanged

        if (jCBano.getSelectedItem() == ""){
            Date myDate = new Date();
            jTdataDe.setText(String.valueOf(myDate.getYear()+1900) +"-"+ String.valueOf(jCBmes.getSelectedIndex()) + "-01");
            jTdataA.setText(String.valueOf(myDate.getYear()+1900) +"-"+ String.valueOf(jCBmes.getSelectedIndex()+1) + "-01");
        } else {
            jTdataDe.setText(jCBano.getSelectedItem() + "-" + String.valueOf(jCBmes.getSelectedIndex()) + "-01");
            jTdataA.setText(jCBano.getSelectedItem() + "-" + String.valueOf(jCBmes.getSelectedIndex()+1) + "-01");
        }
    }//GEN-LAST:event_jCBmesItemStateChanged

    private void jCBanoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBanoItemStateChanged
        if (jCBano.getSelectedItem() ==""){
            Date myDate = new Date();
            jTdataDe.setText(String.valueOf(myDate.getYear()+1900) +"-"+ String.valueOf(jCBmes.getSelectedIndex()) + "-01");
            jTdataA.setText(String.valueOf(myDate.getYear()+1900) +"-"+ String.valueOf(jCBmes.getSelectedIndex()+1) + "-01");
        } else {
            jTdataDe.setText(jCBano.getSelectedItem() + "-" + String.valueOf(jCBmes.getSelectedIndex()) + "-01");
            jTdataA.setText(jCBano.getSelectedItem() + "-" + String.valueOf(jCBmes.getSelectedIndex()+1) + "-01");
        }
    }//GEN-LAST:event_jCBanoItemStateChanged

    private void jBmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBmesActionPerformed

        DefaultTableModel modeloE = (DefaultTableModel) jTentradas.getModel();
        modeloE.setNumRows(0);
        EntradaDAO edao = new EntradaDAO();
        totalentradas = 0;

        for (Entrada e : edao.read_edata(jTdataDe.getText(), jTdataA.getText())) {

            modeloE.addRow(new Object[]{
                e.getId(),
                e.getDes_entrada(),
                e.getData(),
                e.getValor()

            });
            totalentradas=totalentradas+e.getValor();
        }
        txtValorTotalEntradas.setText(String.format("%.2f €",totalentradas));

        DefaultTableModel modeloS = (DefaultTableModel) jTsaidas.getModel();
        modeloS.setNumRows(0);
        SaidaDAO sdao = new SaidaDAO();
        totalsaidas = 0;

        for (Saida s : sdao.read_edata(jTdataDe.getText(), jTdataA.getText())) {

            modeloS.addRow(new Object[]{
                s.getId(),
                s.getDes_saida(),
                s.getData(),
                s.getValor()

            });
            totalsaidas=totalsaidas+s.getValor();
        }
        txtValorTotalSaidas.setText(String.format("%.2f €",totalsaidas));

        Saldo s = new Saldo(totalentradas, totalsaidas);
        txtValorSaldo.setText(s.toString());
    }//GEN-LAST:event_jBmesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBmes;
    private javax.swing.JComboBox<String> jCBano;
    private javax.swing.JComboBox<String> jCBmes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTdataA;
    private javax.swing.JTextField jTdataDe;
    private javax.swing.JTable jTentradas;
    private javax.swing.JTable jTsaidas;
    private javax.swing.JTextField txtValorSaldo;
    private javax.swing.JTextField txtValorTotalEntradas;
    private javax.swing.JTextField txtValorTotalSaidas;
    // End of variables declaration//GEN-END:variables
}
